### ISSUE TITLE
Update match

### ISSUE THREAD

**Issue by chalo2000** [cuappdev/pear-django-backend#8]
Properly update the states as in the diagram below (the update route in this diagram is named /match/availabilities
skipping the dark green line for now as it is not implemented on frontend
<img width="547" alt="matching flow" src="https://user-images.githubusercontent.com/21962778/111840324-989f0480-88d2-11eb-88ec-af2b1b23bc6b.png">

**Comment by chalo2000** [comment]
@noah-solomon can we make sure that the PR you submitted refers to this issue?

**Comment by noah-solomon** [comment]
> @noah-solomon can we make sure that the PR you submitted refers to this issue?

gotchu
